### ISSUE TITLE
Install from PyPI fails silently

### ISSUE THREAD

**Issue by hjheath** [jessepollak/urlmatch#2]
When installing from PyPI the urlmatch-0.0.2.dist-info directory is created, but the package itself is not installed.

I'm not sure how actively you maintain this package, let me know if this is something you have the time and inclination to look at!

**Comment by hjheath** [comment]
@jessepollak could you prioritise this one?

**Comment by jessepollak** [comment]
This is fixed in 0.0.3!

**Comment by jessepollak** [comment]
And by 0.0.3, I mean 1.0.0 since it also shipped the breaking change with booleans.

**Comment by hjheath** [comment]
Sweet - thanks! Could you let me know when you have updated PyPI?

**Comment by jessepollak** [comment]
1.0.0 is published!
