### ISSUE TITLE
Trailing slash is required even when followed by a wildcard.

### ISSUE THREAD

**Issue by bhch** [jessepollak/urlmatch#7]
Example:

    match_pattern = http://test.com/*
    url1 = http://test.com/
    url2 = http://test.com

    urlmatch(match_pattern, url1) -> True
    urlmatch(match_pattern, url2) -> False

I'm using urlmatch to match http referrers against some whitelisted domains. However, some browsers, example Firefox version < 48, don't append slash to the root url in http referrer header. So, even if the request is being made from a whitelisted domain, the http referrer doesn't match the whitelisted url.

I think the trailing slash should be made optional in the url **if in the match_pattern it's followed by a wildcard for path**. 

For example:

    http://test.com/*     # trailing slash optional
    http://test.com/      # trailing slash required

**Comment by bhch** [comment]
One solution that I can think of is to put the `/` in a group and then matching `.*` only if `/` is present.

A very vague example:

     re.match( r'^test.com(\/)?(?(1).*)$', 'test.com/')    # match
     re.match( r'^test.com(\/)?(?(1).*)$', 'test.com')     # match

If only `/` is made optional, then it will match some unintended TLDs as well (however, the above solution is safe to use):

    re.match( r'^test.co(\/)?.*$', 'test.co')       # match
    re.match( r'^test.co(\/)?.*$', 'test.co.uk')    # match
    re.match( r'^test.co(\/)?.*$', 'test.com')      # match

**Comment by hjheath** [comment]
This library is based on the [Chrome match patterns](https://developer.chrome.com/extensions/match_patterns), which always require a path for a valid referrer. There is no clear spec, but the consensus seems to be that referrers should have a trailing slash when the path is empty, see this [discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=1186072).

Therefore I do not think this package should permit an unsupported behaviour by default. However you could do:
```
match_pattern = "http://test.com*"
url1 = "http://test.com/"
url2 = "http://test.com"

urlmatch(match_pattern, url1, path_required=False) # True
urlmatch(match_pattern, url2, path_required=False) # True
```
